server:
  port: 8084
spring:
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          service-host-type: ip
          name: feedback-service
        enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
        registration:
          keycloak:
            client-id: feedback-service-metrics-client
            client-secret: 4cD79sTpV318BqiIWWUYsfjywdzg4DeK
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'